name: Deploy Lambda

on:
  push:
    branches:
      - main
      - release
      - 'feature/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      LAMBDA_ROLE_ARN: ${{ secrets.LAMBDA_ROLE_ARN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Lambda binary with Dockerfile
        run: |
          docker build -t matoolapi .
          docker create --name extract matoolapi
          docker cp extract:/var/runtime/bootstrap ./bootstrap
          docker rm extract
          chmod +x bootstrap
          zip lambda.zip bootstrap

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda Function
        run: |
          FUNCTION_NAME="MaToolAPIv2"

          echo "Deploying Lambda: $FUNCTION_NAME"

          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://lambda.zip

          sleep 10

          # 新しいバージョンを発行
          VERSION=$(aws lambda publish-version --function-name "$FUNCTION_NAME" --query 'Version' --output text)
          echo "Published new version: $VERSION"

          # ブランチ名をエイリアスに紐付け
          BRANCH=${GITHUB_REF_NAME//\//-}
          aws lambda update-alias \
            --function-name "$FUNCTION_NAME" \
            --name "$BRANCH" \
            --function-version "$VERSION" 2>/dev/null \
            || aws lambda create-alias \
              --function-name "$FUNCTION_NAME" \
              --name "$BRANCH" \
              --function-version "$VERSION"

          echo "Lambda alias '$BRANCH' now points to version $VERSION"

      - name: Deploy API Gateway Stage (v2)
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          API_GATEWAY_ID: ${{ secrets.API_GATEWAY_ID }}
        run: |
            set -e

            BRANCH=${GITHUB_REF_NAME//\//-}
            echo "Deploying API Gateway stage: $BRANCH"

            FUNCTION_NAME="MaToolAPIv2"
            
            # --- Add permission for API Gateway to invoke Lambda ---
            aws lambda add-permission \
              --function-name "$FUNCTION_NAME" \
              --statement-id "apigateway-v2-$BRANCH" \
              --action lambda:InvokeFunction \
              --principal apigateway.amazonaws.com \
              || echo "Permission already exists"

            echo "✅ Lambda permission added"

            # --- Get Lambda alias ARN ---
            FUNCTION_ALIAS_ARN=$(aws lambda get-alias \
              --function-name "$FUNCTION_NAME" \
              --name "$BRANCH" \
              --query 'AliasArn' \
              --output text)

            echo "Lambda alias ARN: $FUNCTION_ALIAS_ARN"

            # --- Update API Gateway v2 Integration ---
            # v2ではintegration更新用のURI形式が違う
            aws apigatewayv2 update-integration \
              --api-id "$API_GATEWAY_ID" \
              --integration-id $(aws apigatewayv2 get-integrations \
                                    --api-id "$API_GATEWAY_ID" \
                                    --query "Items[0].IntegrationId" \
                                    --output text) \
              --integration-type AWS_PROXY \
              --integration-uri "arn:aws:apigateway:${AWS_REGION}:lambda:path/2015-03-31/functions/${FUNCTION_ALIAS_ARN}/invocations"

            echo "✅ Integration updated for Lambda alias"

            # --- Deploy API Gateway Stage ---
            aws apigatewayv2 create-deployment \
              --api-id "$API_GATEWAY_ID" \
              --stage-name "$BRANCH"

            echo "✅ API Gateway deployed for stage: $BRANCH"

      - name: Output Lambda Function Name
        run: echo "Lambda function deployed ${FUNCTION_NAME}"

